# Generated by Django 2.1.5 on 2020-08-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='账号名称', max_length=40, verbose_name='账号名称')),
                ('account', models.CharField(help_text='账号', max_length=40, verbose_name='账号')),
                ('bank_name', models.CharField(help_text='开户行名称', max_length=40, verbose_name='开户行名称')),
                ('bank_code', models.CharField(help_text='开户行号', max_length=40, verbose_name='开户行号')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
            },
        ),
        migrations.CreateModel(
            name='BusinessCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司名称', max_length=40, verbose_name='公司名称')),
                ('is_activate', models.BooleanField(default=True, verbose_name='状态')),
                ('mouth_total_max_limit', models.PositiveIntegerField(default=0, help_text='设置为0代表不设置上限', verbose_name='月上限(万元)')),
                ('day_total_max_limit', models.PositiveIntegerField(default=0, help_text='设置为0代表不设置上限', verbose_name='日上限(万元)')),
            ],
            options={
                'verbose_name': '交易公司',
                'verbose_name_plural': '交易公司',
            },
        ),
        migrations.CreateModel(
            name='BusinessScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='经营分类', max_length=40, verbose_name='经营分类')),
                ('is_activate', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '经营分类',
                'verbose_name_plural': '经营分类',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='子公司名称', max_length=40, verbose_name='子公司名称')),
                ('corporation', models.CharField(choices=[('1', '默认集团')], default='1', help_text='子公司所属集团, 默认1', max_length=2, verbose_name='所属集团')),
                ('is_activate', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '集团子公司',
                'verbose_name_plural': '集团子公司',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名称', max_length=40, verbose_name='商品名称')),
                ('type', models.CharField(help_text='商品型号', max_length=511, verbose_name='商品型号')),
                ('price_min', models.PositiveIntegerField(help_text='单价下限(包含)', verbose_name='单价下限')),
                ('price_max', models.PositiveIntegerField(help_text='单价上限(包含)', verbose_name='单价上限')),
                ('unit', models.CharField(help_text='计量单位', max_length=40, verbose_name='计量单位')),
                ('total_range', models.CharField(choices=[('1', '200万以内'), ('2', '200万-500万'), ('3', '超过500万')], help_text='总价范围', max_length=1, verbose_name='总价范围')),
                ('is_activate', models.BooleanField(default=True, verbose_name='状态')),
                ('scope', models.ForeignKey(help_text='大的经营分类', on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('businesscompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.BusinessCompany')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='所属子公司')),
            ],
            options={
                'verbose_name': '买方',
                'verbose_name_plural': '买方',
            },
            bases=('Account.businesscompany',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('businesscompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.BusinessCompany')),
            ],
            options={
                'verbose_name': '卖方',
                'verbose_name_plural': '卖方',
            },
            bases=('Account.businesscompany',),
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='公司经营分类'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='所属集团子公司'),
        ),
    ]
