# Generated by Django 2.1.5 on 2020-08-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='账号名称', max_length=40, verbose_name='账号名称')),
                ('account', models.CharField(help_text='账号', max_length=40, verbose_name='账号')),
                ('bank_name', models.CharField(help_text='开户行名称', max_length=40, verbose_name='开户行名称')),
                ('bank_code', models.CharField(help_text='开户行联行号', max_length=40, verbose_name='开户行联行号')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
            },
        ),
        migrations.CreateModel(
            name='BusinessCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='企业名称', max_length=100, verbose_name='企业名称')),
                ('corporation', models.CharField(blank=True, help_text='企业法人姓名', max_length=20, null=True, verbose_name='企业法人姓名')),
                ('registered_capital', models.IntegerField(blank=True, help_text='企业注册资金', null=True, verbose_name='企业注册资金')),
                ('registered_capital_currency', models.CharField(blank=True, default='元人名币', help_text='注册资金币种', max_length=10, null=True, verbose_name='注册资金币种')),
                ('registered_province', models.CharField(blank=True, help_text='注册省份', max_length=15, null=True, verbose_name='注册省份')),
                ('telphone', models.CharField(blank=True, help_text='企业办公电话', max_length=15, null=True, verbose_name='企业办公电话')),
                ('is_activate', models.BooleanField(blank=True, default=True, help_text='该公司是否继续使用', null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '交易公司',
                'verbose_name_plural': '交易公司',
            },
        ),
        migrations.CreateModel(
            name='BusinessScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='经营分类', max_length=40, verbose_name='经营分类')),
                ('is_activate', models.BooleanField(blank=True, default=True, help_text='该分类是否继续使用', null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '经营分类',
                'verbose_name_plural': '经营分类',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='子公司名称', max_length=40, verbose_name='子公司名称')),
                ('is_activate', models.BooleanField(blank=True, default=True, help_text='该公司是否继续使用', null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '集团子公司',
                'verbose_name_plural': '集团子公司',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='交易场所', max_length=40, verbose_name='交易场所')),
                ('template', models.CharField(choices=[('1', '福建模板'), ('2', '江西模板')], default='1', max_length=2, verbose_name='文件模板')),
                ('is_activate', models.BooleanField(blank=True, default=True, help_text='该交易场所是否继续使用', null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '交易场所',
                'verbose_name_plural': '交易场所',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名称', max_length=40, verbose_name='商品名称')),
                ('type', models.CharField(help_text='商品型号', max_length=511, verbose_name='商品型号')),
                ('price_min', models.PositiveIntegerField(help_text='单价下限(包含)', verbose_name='单价下限')),
                ('price_max', models.PositiveIntegerField(help_text='单价上限(包含)', verbose_name='单价上限')),
                ('unit', models.CharField(help_text='计量单位', max_length=40, verbose_name='计量单位')),
                ('total_range', models.CharField(choices=[('1', '200万以内'), ('2', '200万-500万'), ('3', '超过500万')], help_text='单笔定金范围', max_length=1, verbose_name='单笔定金范围')),
                ('is_activate', models.BooleanField(blank=True, default=True, help_text='该商品是否继续使用', null=True, verbose_name='状态')),
                ('scope', models.ForeignKey(help_text='大的经营分类', on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('businesscompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.BusinessCompany')),
            ],
            options={
                'verbose_name': '买方',
                'verbose_name_plural': '买方',
            },
            bases=('Account.businesscompany',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('businesscompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.BusinessCompany')),
            ],
            options={
                'verbose_name': '卖方',
                'verbose_name_plural': '卖方',
            },
            bases=('Account.businesscompany',),
        ),
        migrations.AddField(
            model_name='company',
            name='corporation',
            field=models.ForeignKey(help_text='子公司所属集团, 默认1', on_delete=django.db.models.deletion.PROTECT, to='Account.Corporation', verbose_name='所属集团'),
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='企业经营分类'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='所属集团子公司'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='所属集团子公司'),
        ),
    ]
