# Generated by Django 2.1.5 on 2020-08-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscompany',
            name='registered_capital',
            field=models.IntegerField(blank=True, help_text='企业注册资金', null=True, verbose_name='企业注册资金(元)'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(help_text='交易场所', max_length=40, verbose_name='交易场所名称'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='template',
            field=models.CharField(choices=[('1', '福建模板'), ('2', '江西模板')], default='1', max_length=2, verbose_name='转账文件模板'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_max',
            field=models.PositiveIntegerField(help_text='单价上限(元)', verbose_name='单价上限'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_min',
            field=models.PositiveIntegerField(help_text='单价下限(元)', verbose_name='单价下限'),
        ),
    ]
