# Generated by Django 2.1.5 on 2020-08-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品型号', max_length=511, verbose_name='商品型号')),
                ('price_min', models.PositiveIntegerField(help_text='单价下限(包含)', verbose_name='单价下限')),
                ('price_max', models.PositiveIntegerField(help_text='单价上限(包含)', verbose_name='单价上限')),
                ('unit', models.CharField(help_text='计量单位', max_length=40, verbose_name='计量单位')),
                ('total_range', models.CharField(choices=[('1', '200万以内'), ('2', '200万-500万'), ('3', '超过500万')], help_text='总价范围', max_length=1, verbose_name='总价范围')),
                ('is_activate', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.AddField(
            model_name='businessscope',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='products',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='公司经营分类'),
        ),
    ]
