# Generated by Django 2.1.5 on 2020-08-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, default='', help_text='子公司代码', max_length=10, null=True, verbose_name='子公司代码'),
        ),
    ]
