# Generated by Django 2.1.5 on 2020-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscompany',
            name='day_total_max_limit',
        ),
        migrations.RemoveField(
            model_name='businesscompany',
            name='mouth_total_max_limit',
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='corporation',
            field=models.CharField(blank=True, help_text='企业法人姓名', max_length=20, null=True, verbose_name='企业法人姓名'),
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='registered_capital',
            field=models.IntegerField(blank=True, help_text='企业注册资金', null=True, verbose_name='企业注册资金'),
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='registered_capital_currency',
            field=models.CharField(blank=True, default='元人名币', help_text='注册资金币种', max_length=10, null=True, verbose_name='注册资金币种'),
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='registered_province',
            field=models.CharField(blank=True, help_text='注册省份', max_length=15, null=True, verbose_name='注册省份'),
        ),
        migrations.AddField(
            model_name='businesscompany',
            name='telphone',
            field=models.CharField(blank=True, help_text='企业办公电话', max_length=15, null=True, verbose_name='企业办公电话'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_code',
            field=models.CharField(help_text='开户行联行号', max_length=40, verbose_name='开户行联行号'),
        ),
        migrations.AlterField(
            model_name='businesscompany',
            name='name',
            field=models.CharField(help_text='企业名称', max_length=100, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='businesscompany',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='企业经营分类'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='所属集团子公司'),
        ),
    ]
