# Generated by Django 2.1.5 on 2020-08-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200803_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='商品名称', max_length=511, verbose_name='商品型号'),
        ),
        migrations.AlterField(
            model_name='products',
            name='scope',
            field=models.ForeignKey(help_text='大的经营分类', on_delete=django.db.models.deletion.PROTECT, to='Account.BusinessScope', verbose_name='分类'),
        ),
    ]
