# Generated by Django 2.1.5 on 2020-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200804_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='total_range',
            field=models.CharField(choices=[('1', '200万以内'), ('2', '200万-500万'), ('3', '超过500万')], help_text='单笔定金范围', max_length=1, verbose_name='单笔定金范围'),
        ),
    ]
