# Generated by Django 2.1.5 on 2020-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200805_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscompany',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, help_text='该公司是否继续使用', null=True, verbose_name='状态'),
        ),
    ]
