# Generated by Django 2.1.5 on 2020-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200803_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(default='', help_text='商品名称', max_length=511, verbose_name='商品型号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='经营分类', max_length=40, verbose_name='商品名称'),
        ),
    ]
