# Generated by Django 2.1.5 on 2020-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200803_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='商品名称', max_length=40, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(help_text='商品型号', max_length=511, verbose_name='商品型号'),
        ),
    ]
