# Generated by Django 2.1.5 on 2020-08-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200805_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='集团名称', max_length=40, verbose_name='集团名称')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='corporation',
            field=models.ForeignKey(help_text='子公司所属集团, 默认1', on_delete=django.db.models.deletion.PROTECT, to='Account.Corporation', verbose_name='所属集团'),
        ),
    ]
