# Generated by Django 2.1.5 on 2020-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200805_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='template',
            field=models.CharField(choices=[('1', '福建模板'), ('2', '江西模板')], default='1', max_length=2, verbose_name='文件模板'),
        ),
    ]
