# Generated by Django 2.1.5 on 2020-08-31 16:26

import Tran.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='任务日期')),
                ('name', models.CharField(blank=True, help_text='同一日有多个任务最好设置本次任务名称', max_length=40, null=True, verbose_name='任务名称')),
                ('amount_total_min', models.PositiveIntegerField(help_text='每日总金额下限(万元),建议值2000', verbose_name='每日总金额下限(万元)')),
                ('amount_total_max', models.PositiveIntegerField(help_text='每日总金额上限(万元),建议值4000', verbose_name='每日总金额上限(万元)')),
                ('batch_total', models.PositiveSmallIntegerField(help_text='每个任务生成的excel转账文件数,建议值15-30', verbose_name='批次数')),
                ('batch_num_min', models.PositiveSmallIntegerField(help_text='每批次交易笔数下限,建议值3', verbose_name='每批次交易笔数下限')),
                ('batch_num_max', models.PositiveSmallIntegerField(help_text='每批次交易笔数上限,建议值5', verbose_name='每批次交易笔数上限')),
                ('status', models.BooleanField(default=False, verbose_name='是否完成')),
                ('remark', models.CharField(blank=True, help_text='该备注信息会自动填充到每笔转账备注中', max_length=40, null=True, verbose_name='交易备注')),
                ('file_no', models.CharField(default=Tran.models.random_str, max_length=6, verbose_name='文件编号')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Corporation', verbose_name='所属交易场所')),
            ],
            options={
                'verbose_name': '每日任务',
                'verbose_name_plural': '每日任务',
            },
        ),
        migrations.CreateModel(
            name='TaskBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.PositiveIntegerField(verbose_name='批次总金额(万元)')),
                ('batch_total', models.PositiveSmallIntegerField(default=3, verbose_name='批次交易笔数')),
                ('num', models.PositiveSmallIntegerField(verbose_name='批次编号')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tran.Task', verbose_name='所属日任务')),
            ],
            options={
                'verbose_name': '任务批次',
                'verbose_name_plural': '任务批次',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='任务日期')),
                ('amount', models.IntegerField(help_text='交易定金金额', verbose_name='定金金额(万元)')),
                ('total_range', models.CharField(choices=[('1', '200万以内'), ('2', '200万-500万'), ('3', '超过500万'), ('4', '500万以内'), ('5', '200万以上'), ('6', '不限金额')], help_text='总价范围', max_length=1, verbose_name='总价范围')),
                ('price', models.PositiveIntegerField(help_text='购买单价', verbose_name='购买单价(元)')),
                ('tran_tatal', models.IntegerField(help_text='交易定金金额', verbose_name='订货金额(元)')),
                ('quantity', models.FloatField(help_text='订货量', verbose_name='订货量')),
                ('order_no', models.CharField(blank=True, default='', help_text='订单号', max_length=30, null=True, verbose_name='订单号')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Buyer', verbose_name='买方')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Products', verbose_name='购买商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Seller', verbose_name='卖方')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tran.Task', verbose_name='所属日任务')),
                ('task_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tran.TaskBatch', verbose_name='所属日批次')),
            ],
            options={
                'verbose_name': '交易明细',
                'verbose_name_plural': '交易明细',
            },
        ),
    ]
