# Generated by Django 2.1.5 on 2020-08-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount_total_max',
            field=models.PositiveIntegerField(verbose_name='每日总金额上限(万元)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='amount_total_min',
            field=models.PositiveIntegerField(verbose_name='每日总金额下限(万元)'),
        ),
        migrations.AlterField(
            model_name='taskbatch',
            name='amount_total',
            field=models.PositiveIntegerField(verbose_name='批次总金额(万元)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(help_text='交易定金金额', verbose_name='定金金额(万元)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(help_text='购买单价', verbose_name='购买单价(元)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_tatal',
            field=models.IntegerField(help_text='交易定金金额', verbose_name='订货金额(万元)'),
        ),
    ]
