# Generated by Django 2.1.5 on 2020-08-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200804_1137'),
        ('Tran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='购买单价', verbose_name='购买单价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Account.Products', verbose_name='购买商品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='订货量', verbose_name='订货量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_range',
            field=models.CharField(choices=[('1', '200万以内'), ('2', '200万-500万'), ('3', '超过500万')], default=1, help_text='总价范围', max_length=1, verbose_name='总价范围'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tran_tatal',
            field=models.IntegerField(default=0, help_text='交易定金金额', verbose_name='订货金额'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(help_text='交易定金金额', verbose_name='定金金额'),
        ),
    ]
