# Generated by Django 2.1 on 2020-06-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_batch_total',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='已完成批次数'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', '任务未开始'), ('10', '批次生成中'), ('11', '批次生成完成'), ('90', '当日批次生成完成'), ('99', '任务作废')], default='1', max_length=2, verbose_name='任务状态'),
        ),
    ]
