# Generated by Django 2.1 on 2020-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0002_auto_20200615_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='has_batch_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已完成批次数'),
        ),
    ]
