# Generated by Django 2.1.5 on 2020-08-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0002_auto_20200805_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount_total_max',
            field=models.PositiveIntegerField(default=4000, verbose_name='每日总金额上限(万元)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='amount_total_min',
            field=models.PositiveIntegerField(default=2000, verbose_name='每日总金额下限(万元)'),
        ),
    ]
