# Generated by Django 2.1.5 on 2020-08-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0002_auto_20200804_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
    ]
