# Generated by Django 2.1.5 on 2020-08-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0003_auto_20200805_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='corporation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Account.Corporation', verbose_name='所属交易场所'),
        ),
    ]
