# Generated by Django 2.1.5 on 2020-08-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20200805_1030'),
        ('Tran', '0003_remove_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='corporation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Account.Corporation', verbose_name='所属交易场所'),
            preserve_default=False,
        ),
    ]
