# Generated by Django 2.1 on 2020-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0003_auto_20200615_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='has_batch_total',
        ),
        migrations.RemoveField(
            model_name='taskbatch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
