# Generated by Django 2.1 on 2020-06-16 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tran', '0004_auto_20200615_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='任务日期'),
        ),
    ]
