# Generated by Django 2.1 on 2020-06-16 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='任务日期')),
                ('amount_total', models.IntegerField(default=0, verbose_name='日总交易金额(万元)')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Buyer', verbose_name='买方')),
            ],
            options={
                'verbose_name': '日买方交易额总量',
                'verbose_name_plural': '日买方交易额总量',
            },
        ),
        migrations.CreateModel(
            name='DaySeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='任务日期')),
                ('amount_total', models.IntegerField(default=0, verbose_name='日总交易金额(万元)')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Seller', verbose_name='卖方')),
            ],
            options={
                'verbose_name': '日卖方交易额总量',
                'verbose_name_plural': '日卖方交易额总量',
            },
        ),
        migrations.CreateModel(
            name='MouthBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=6, null=True, verbose_name='月份')),
                ('amount_total', models.IntegerField(default=0, verbose_name='月总交易金额(万元)')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Buyer', verbose_name='买方')),
            ],
            options={
                'verbose_name': '月买方交易额总量',
                'verbose_name_plural': '月买方交易额总量',
            },
        ),
        migrations.CreateModel(
            name='MouthSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=6, null=True, verbose_name='月份')),
                ('amount_total', models.IntegerField(default=0, verbose_name='月总交易金额(万元)')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Seller', verbose_name='卖方')),
            ],
            options={
                'verbose_name': '月卖方交易额总量',
                'verbose_name_plural': '月卖方交易额总量',
            },
        ),
    ]
