# Generated by Django 2.1.5 on 2020-06-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='集团子公司'),
        ),
        migrations.AlterField(
            model_name='mouthcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Company', verbose_name='集团子公司'),
        ),
    ]
