# Generated by Django 2.1.5 on 2020-08-04 17:42

import Statistics.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200804_1137'),
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySellerProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='任务日期')),
                ('price', models.PositiveIntegerField(help_text='购买单价', verbose_name='购买单价')),
                ('quantity', models.PositiveIntegerField(help_text='订货量', verbose_name='订货量')),
                ('choice_scale', models.PositiveIntegerField(default=Statistics.models.DaySellerProducts.random_choice_scale, help_text='备货比例', verbose_name='备货比例')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Products', verbose_name='购买商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Seller', verbose_name='卖方')),
            ],
            options={
                'verbose_name': '卖方每日销售表',
                'verbose_name_plural': '卖方每日销售表',
            },
        ),
    ]
