# Generated by Django 2.1.5 on 2020-08-05 11:35

import Statistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_daysellerproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysellerproducts',
            name='choice_scale',
            field=models.PositiveIntegerField(blank=True, default=Statistics.models.DaySellerProducts.random_choice_scale, help_text='备货比例', null=True, verbose_name='备货比例'),
        ),
        migrations.AlterField(
            model_name='daysellerproducts',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='购买单价', null=True, verbose_name='购买单价'),
        ),
        migrations.AlterField(
            model_name='daysellerproducts',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='订货量', null=True, verbose_name='订货量'),
        ),
    ]
