# Generated by Django 2.1.5 on 2020-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0003_auto_20200805_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysellerproducts',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='购买单价', null=True, verbose_name='购买单价'),
        ),
        migrations.AlterField(
            model_name='daysellerproducts',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='订货量', null=True, verbose_name='订货量'),
        ),
    ]
